# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Nect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nect
  pod 'Parse'
  pod 'Parse/UI'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
pod 'ChatSDK'
pod 'ChatSDKFirebase/Adapter'
pod 'ChatSDKFirebase/FileStorage'
pod 'ChatSDKFirebase/Push'
pod 'Unirest', '~> 1.1.4'
  #platform :ios, '5.0'


end
