# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nect
  pod 'Parse'
  pod 'Parse/UI'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  platform :ios, '5.0'
pod 'Unirest', '~> 1.1.4'

end
